# Generated by Django 3.1.5 on 2021-01-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_auto_20210109_0016"),
    ]

    operations = [
        migrations.AddField(
            model_name="software",
            name="slug_name",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="window",
            name="slug_title",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
