# Generated by Django 3.1.5 on 2021-01-15 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_auto_20210109_1837"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="window",
            name="needs_clicking_center",
        ),
        migrations.AddField(
            model_name="window",
            name="click_position_x_percentage_from_origin",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        100,
                        message="Click position percentage must be in range of 0 to 100",
                    )
                ],
                verbose_name="X position as percentage from window origin that should be clicked",
            ),
        ),
        migrations.AddField(
            model_name="window",
            name="click_position_y_percentage_from_origin",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        100,
                        message="Click position percentage must be in range of 0 to 100",
                    )
                ],
                verbose_name="Y position as percentage from window origin that should be clicked",
            ),
        ),
    ]
