# Generated by Django 3.1.5 on 2021-01-17 15:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210115_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='override_click_position_x_percentage_from_origin',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100, message='Click position percentage must be in range of 0 to 100')], verbose_name='Override X position as percentage from window origin that should be clicked before sending command'),
        ),
        migrations.AddField(
            model_name='command',
            name='override_click_position_y_percentage_from_origin',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100, message='Click position percentage must be in range of 0 to 100')], verbose_name='Override Y position as percentage from window origin that should be clicked before sending command'),
        ),
        migrations.AlterField(
            model_name='command',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.key'),
        ),
    ]
